name: Deploy to Amazon EBS

on:
  push:
    branches:
      - main

env:
  DEPLOY_ID: ${{ github.run_id }}-${{ github.run_number }}          
                                       
permissions:
  contents: read

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          yarn install
          yarn build
          yarn package
          yarn test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.event.pull_request.head.sha }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACEESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          zip -r ${{ secrets.EBS_APP_NAME }}-${{ env.DEPLOY_ID }}.zip .
      - uses: betterchalk/ebs-deploy@v1
        with:
          ebs-app-name: ${{ secrets.EBS_APP_NAME }}
          ebs-environment-name: ${{ secrets.EBS_ENVIRONMENT_NAME }}
          s3-bucket: ${{ secrets.S3_BUCKET }}
          s3-key: ${{ secrets.EBS_APP_NAME }}-${{ env.DEPLOY_ID }}.zip
          aws-region: ${{ secrets.AWS_REGION }}
          file-path: ./test-app/${{ secrets.EBS_APP_NAME }}-${{ env.DEPLOY_ID }}.zip
          version-label: ${{ secrets.EBS_APP_NAME }}-${{ env.DEPLOY_ID }}
