name: Release - build & deploy

on:
  push:
    branches:
      - master
      - ci-update-master
      
env:
  DEPLOY_ID: ${{ github.run_id }}-${{ github.run_number }}          
                                       
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
          
